version: '3.8'

networks:
  cinema_net:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cinema
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --notify-keyspace-events "Ex"
    volumes:
      - redis_data:/data
    networks:
      - cinema_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cinema_net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Configuração CRÍTICA para funcionar dentro e fora do Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cinema_net

  # Serviço 1: Backend gRPC + Producer Kafka
  booking-service:
    build: .
    container_name: booking_service
    command: python booking_service_server.py
    environment:
      - REDIS_HOST=redis-cinema
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
      - SMTP_PASSWORD=${SMTP_PASSWORD} # Pega do .env
    depends_on:
      - redis
      - kafka
    networks:
      - cinema_net

# Serviço 2: Frontend + WebSocket
  websocket-server:
    build: .
    container_name: websocket_server
    command: python -m uvicorn websocket_server:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GRPC_HOST=booking_service
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - REDIS_HOST=redis-cinema  # <--- ADICIONE ESTA LINHA
    depends_on:
      - booking-service
      - redis                    # <--- ADICIONE ESTA LINHA (boa prática)
    networks:
      - cinema_net

  # Serviço 3: Redis Listener
  redis-listener:
    build: .
    container_name: redis_listener
    command: python redis_listener.py
    environment:
      - REDIS_HOST=redis-cinema
      - WS_HOST=websocket_server
    depends_on:
      - redis
      - websocket-server
    networks:
      - cinema_net

  # Serviço 4: Consumer Kafka
  notification-consumer:
    build: .
    container_name: notification_consumer
    command: python notification_consumer.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:29092
    depends_on:
      - kafka
    networks:
      - cinema_net

volumes:
  redis_data: {}